### ISSUE TITLE
USB-C Speisung

### ISSUE THREAD

**Issue by TheguyfromWallisellen** [msw-winterthur/uC_Board#13]
Das uC-Board kann nur mit einem "Dummen" PSU betrieben werden. Es währe nicht schlecht, wenn wir die CC Pins mit einem Pull-Down Widerstand verbinden würden. So könnte man mit einem "schlauen" PSU das uC-Board speisen.

--> Hier noch der link zum USB-C Stecker, wo alles nochmals beschrieben wird. 
https://www.allaboutcircuits.com/technical-articles/introduction-to-usb-type-c-which-pins-power-delivery-data-transfer/

**Comment by DarioMSW** [comment]
Hallo und vielen Dank für deinen Beitrag!

Wenn ich den Beitrag richtig verstehe, soll CC1 und CC2 je mit einem PullDown versehen werden. Wie gross sollen die PullDowns sein?

Gruss

**Comment by TheguyfromWallisellen** [comment]
Ich habe im Internet nachgeschaut und habe gefunden, dass ich einen 5.1k widerstand nehmen sollte. Ich habe es ausprobiert und bin zum schluss gekommen, dass es auch funktioniert. Mit 10k (wie wir es im Unterricht angeschaut haben) hatte ich nicht so glück. Es funktionierte nicht.

Im Bild habe ich nur einen Pulldown-Resistor drin. Es währe jedoch wichtig, dass man dann im Layout auch den zweiten CC-Pin runterziehen muss, da es sonst nur funktionieren würde, wenn das Kabel gerade richtig eingesteckt ist. Ausserdem sollten die beiden CC-Pins nicht kurzgeschlossen und dann auf GND gezogen werden, sondern beide separat heruntergezogen werden.

![WhatsApp Image 2023-10-09 at 14 19 15_859b871c](https://github.com/msw-winterthur/uC_Board/assets/147142917/15b8c32e-922e-41c2-ab2f-16311f948793)

**Comment by DarioMSW** [comment]
Wir brauchen 5V, 2A

Hätte ein Bauteil wie der HUSB238 einen Vorteil gegenüber der Lösung mit Widerständen?
https://en.hynetek.com/2421.html

**Comment by TheguyfromWallisellen** [comment]
Hoi Dario,

Ich da hat sich wohl ein Fehler eingeschlichen.

So wie ich es verstanden habe, sollte es möglich sein, damit 3A zu ziehen. Jedoch währe es nicht schlecht, wenn du dir noch das PDF anschaust, damit wir beide sicher sind.

Wenn du möchtest, kann ich auch diese Schaltung noch diese Woche Testen und dir die Resultate dokumentiert zusenden.

Deine Lösung ist auch gut, da aber unser Board nur 5v 3A brauchen kann währe es nicht kosteneffektiv noch einen Zusätzlichen IC zu verwenden.

Ich habe die relevantesten Seiten aus dem PDF kopiert und habe sie dir in den Anhang hochgeladen.



Herzliche Grüsse

***@***.***

Petar Lisinac
Lernender Elektroniker

Zeughausstrasse 56
8400 Winterthur
***@***.******@***.***>
Mobile: +41 76 377 02 53

Von: DarioMSW ***@***.***>
Gesendet: Friday, 27 October 2023 10:30
An: msw-winterthur/uC_Board ***@***.***>
Cc: Petar Lisinac ***@***.***>; Author ***@***.***>
Betreff: Re: [msw-winterthur/uC_Board] USB-C Speisung (Issue #13)


Wir brauchen 5V, 2A

Hätte ein Bauteil wie der HUSB238 einen Vorteil gegenüber der Lösung mit Widerständen?
https://en.hynetek.com/2421.html

**Comment by DarioMSW** [comment]
Closed by d8044bb4e5b6088d9496e6cb1a93cc85671affd4
