### ISSUE TITLE
Led Helligkeit einstellen

### ISSUE THREAD

**Issue by Finnja05** [msw-winterthur/uC_Board#16]
Mithilfe eines Potentiometer die Helligkeit der Leds einstellen
Für das 50k Ohm Poti nicht das Poti vom ucBoard nehmen, sondern ein grösseres. 
Schema (Schalter ignorieren): 
![grafik](https://github.com/user-attachments/assets/e22309f8-f933-49fa-9f0f-55aab7031e9c)

**Comment by DarioMSW** [comment]
Merci viel mal! Vollständigkeitshalber hier noch die Berechnungen dazu:
![PXL_20240719_081146013](https://github.com/user-attachments/assets/447867e6-e5d6-4e8e-97f3-bab7ab01ffc2)

**Comment by DarioMSW** [comment]
Und das ursprüngliche Schema:
![grafik](https://github.com/user-attachments/assets/f6a41d1f-cb50-4a5c-bd5d-3b8be55838c5)

Quelle: [https://www.allaboutcircuits.com/technical-articles/how-to-design-schmitt-trigger-oscillators/](https://www.allaboutcircuits.com/technical-articles/how-to-design-schmitt-trigger-oscillators/)

**Comment by DarioMSW** [comment]
Alles übernommen, sogar für die Power LED. siehe 0665441639059580f35105c3dec4148b134ef4a0
